- contrib/manyclangs-run
This updated `manyclangs-run` adds support for an environment variable called `USE_DOCKER_QEMU`. 
When set to a supported architecture (only aarch64 supported atm), `manyclangs-run` will attempt to use our docker image with qemu to link and run the non-native binaries.  
One functional difference that is being introduced here is that the time reported by manyclangs-run now only includes the actual extract time (previously it included the time it took to link as well). I could not figure out a way to "link and then run" without having to pay the cost for spinning up two docker containers when using USE_DOCKER_QEMU. I belive this is not very significant. 
(I think we can 1) docker create, 2) docker start, 3) docker exec for each command, but handling the lifetime of the containers in that …
> Add docker qemu support

- README.md
* Singular "build" instead of plural.
* Remove hyphen from "highly appreciated".
> Fix small typos in `README.md`

- src/atomicfile.rs
- src/bin/elfshaker/show.rs
- src/packidx.rs
- src/repo/error.rs
- src/repo/fs.rs
- src/repo/mod.rs
- src/repo/pack.rs
- src/repo/repository.rs
I have wrapped all errors returned when
opening a file to include the associated file paths.
Closes #7.
> Make I/O errors more informative

- src/atomicfile.rs
- src/bin/elfshaker/find.rs
- src/bin/elfshaker/list.rs
- src/bin/elfshaker/pack.rs
- src/bin/elfshaker/show.rs
- src/packidx.rs
- src/repo/algo.rs
- src/repo/pack.rs
- src/repo/repository.rs
This represents a pretty significant improvement for the loading times for various operations in a repository with a large number of packs and snapshots. I've looked at all uses of `load_index` and replaced them with `load_index_snapshots` where only the snapshot names or count is used.
For me, this reduces the CPU time to list from 3s down to 10ms, and the win comes from not parsing the whole index.
> Use deserialize_only_snapshots and clippy fixes

- contrib/compdb2line/main.go
- contrib/manyclangs-build
- contrib/manyclangs-build-month
This fixes a few issues I've encountered in the build scripts. Please see the individual commits.
* `link.sh` should report an error if the prerequisites are missing (elfshaker/manyclangs#5).
* Remove the filter_dupes hack and use --start-lib and --end-lib which does the same thing but better, providing binaries which should be equivalent to those you'd get if you had build the archives.
* Fix a bug where comm and jq could diverge.
* Other minor cleanups.
> Buildscript improvements

- src/bin/elfshaker/clone.rs
- src/bin/elfshaker/extract.rs
- src/bin/elfshaker/find.rs
- src/bin/elfshaker/list.rs
- src/bin/elfshaker/list_files.rs
- src/bin/elfshaker/list_packs.rs
- src/bin/elfshaker/main.rs
- src/bin/elfshaker/pack.rs
- src/bin/elfshaker/show.rs
- src/bin/elfshaker/store.rs
- src/bin/elfshaker/update.rs
- src/bin/elfshaker/utils.rs
- src/repo/constants.rs
- src/repo/pack.rs
- src/repo/repository.rs
- test-scripts/check.sh
Allow the user to specify an alternative path for the elfshaker repository directory (elfshaker_data) via `--data-dir`.
Related: #86
> Support changing of the elfshaker data directory

- src/bin/elfshaker/list.rs
- src/packidx.rs
`elfshaker list` in the manyclangs repo used to take 2.12s s to run on my machine and now takes just 0.18s.
> `elfshaker list` performance improvements

- Cargo.lock
- docs/users/installing.md
- flake.lock
- flake.nix
- src/atomicfile.rs
- src/bin/elfshaker/clone.rs
- src/bin/elfshaker/extract.rs
- src/bin/elfshaker/gc.rs
- src/bin/elfshaker/list.rs
- src/bin/elfshaker/list_files.rs
- src/bin/elfshaker/list_packs.rs
- src/bin/elfshaker/pack.rs
- src/bin/elfshaker/show.rs
- src/bin/elfshaker/store.rs
- src/bin/elfshaker/utils.rs
- src/packidx.rs
- src/progress.rs
- src/repo/error.rs
- src/repo/fs.rs
- src/repo/pack.rs
- src/repo/remote.rs
- src/repo/repository.rs
I've been doing a bit of elfshaker hacking recently. Let's get the nitty/straightforward stuff out of the way first since it otherwise gets in the way of development by making you revisit warnings.
As a note, I'm developing with Cargo stable, which is 1.67.0; I haven't tested older versions to see what the eldest we can support is. For now I'm thinking so long as we don't depend on something 'more recent than stable at a given moment', this is a reasonable thing to do, but the included nix changes also make it straightforward to test different rust versions if we want to figure out what the eldest we support is at some point.
In this PR:
* Run `cargo update`. I've not dug in here as much as I would like but it looks mostly straightforward. It looks like some of our dependencies added …
> General maintenance: clippy, fmt, updates, add flake

- contrib/git-list-between
Git's walking mechanism stops as soon as it sees a commit which is older than the date specified by --since.
This is problematic in LLVM's commit history in August 2022, because there is a commit in the middle of it with a CommitDate in 2021.
Work around this by considering a large number of commits and taking the oldest one matching the target date. I'll do the August pack build and confirm that everything is OK before merging this.
Fix #89.
Signed-off-by: Peter Waller <peter.waller@arm.com>
> Workaround git log --since missing commits

- docs/contributors/contributing.md
I haven't run tests locally on any of my recent documentation PRs. I hope that is okay and want to change the published policy to indicate that it is.
Also fixes a typo.
> Don't ask folks to run tests locally on documentation-only PRs [doc]

- docs/users/usage.md
Grammatically, "A snapshot stores a directory state" is more correct than "A snapshot store a directory state". This matters because, with the current wording, it is easier to mistakenly interpret "Snapshot" as a verb instead of a noun in this context.
> Slightly clarify what a snapshot is in usage.md [doc] [fix typo]

- docs/users/installing.md
- Add missing step to download the source code
- Change formatting to match the formatting of the above instructions for using prebuilt binaries
> Update instructions for building from source [doc]

- src/bin/elfshaker/list.rs
- src/bin/elfshaker/list_files.rs
- src/packidx.rs
- src/repo/fs.rs
- src/repo/pack.rs
- src/repo/remote.rs
- src/repo/repository.rs
- test-scripts/check.sh
Add a notion of FileMetadata (describing file state), as distinct from
ObjectMetadata (which describes objects in the store) which is stored in
the FileHandle and therefore on disk as part of snapshot_deltas.
FileMetadata is intended to be extensible but in the first instance
describes file modes bits. In the future it may also describe mtime and
I can imagine further uses arising.
[Note, I've edited this body to reflect the new approach, much of it
remains true from before and stays the same]
Users of the main branch, please note I forsee further potential version
bumps for additional functionality in the near future. If you're using
elfshaker in anger to make long term packs you may want to hold off
making those packs so you get the extra benefits, though it should work
aside from the …
> Preserve File Modes

- .github/workflows/clippy.yml
- .github/workflows/rust.yml
- .github/workflows/test-nix.yml
- Cargo.lock
- Cargo.toml
- elfshaker.nix
- flake.lock
- flake.nix
- src/bin/elfshaker/main.rs
- test-scripts/check.sh
* Bump the version number to 1.0.0-rc1 (note, the RC won't be official until it's tagged and there are binaries on the release page).
* Fix elfshaker --version showing the version number
* Update the nix build infrastructure so that cross compiling works better. Not all cross configurations work, so we'll need a Linux builder and two Darwin builders (aarch64/x86) if we want a full(ish) complement of binaries. See notes in the commit message.
The key is that you can type `nix build .#release` and you'll get the cross-built release artefacts that your machine is capable of building.
They should be reproducible since everything is locked to a specific revision. I've also got all of the build dependencies in a cachix.org cache that the build infrastructure can use so it should be fairly fast …
> Add release machinery

- contrib/manyclangs-run
The `.o` needs to be relative to the elfshaker dir, otherwise we will look it up in the current directory
> Make manyclangs-run work outside the ELFSHAKER directory

- .github/workflows/test-nix.yml
- src/atomicfile.rs
An attempt to fix the atomicfile issue which cropped up in #66; if this doesn't fix it, I suggest we remove the atomicfile api. I would still like to make use of this, but at the end of the day it would still exist in the git history to be resurrected if it were deleted.
> Atomicfile fixes

- src/lib.rs
- src/packidx.rs
- src/repo/fs.rs
- src/repo/pack.rs
- src/repo/repository.rs
This makes the build pass on Windows, however, there is likely more work to make sure we actually work correctly. 
The tests script that we have cannot be run on Windows easily, so we cannot verify that we actually function. My feeling is the best approach is likely to rewrite the functional tests we have in Rust and run them via cargo in the same way. It appears one of the ways to deal with expensive tests is to mark them as ignored, then run them when desired with `cargo test -- --ignored`. https://github.com/rust-lang/rust/blob/054b7b7/src/libcoretest/num/flt2dec/strategy/grisu.rs#L56
> Make elfshaker build on Windows

- Cargo.lock
- elfshaker.nix
- flake.lock
- flake.nix
- src/entrypool.rs
- src/packidx.rs
- **flake.lock: Update**
- **Bump nixpkgs input to 24.05**
- **Run cargo update**
- **Avoid cross-compile to x86-windows from aarch64-linux**
- **Fix new clippy lints**
Yearly dependency bump...
I didn't especially want to do a bump after the rc, but the CI needs fixing; it broke because the github clippy check got too new and breaks on some of our dependencies.
> Bump dependencies to 2024

- src/repo/repository.rs
* Add a docstring
* Parallelise loose entry extraction - leads to a ~20x performance boost if the loose entries live on NFS.
Use case is to be able to have many builds available on NFS pre-pack, since packing is expensive, so we can have a builder which keeps as up to date as possible.
> Parallelise loose entry copying

- src/repo/error.rs
- src/repo/repository.rs
Previously:
```
[ERROR (main) 29.042µs]: *FATAL*: No such file or directory (os error 2) (NotFound)
```
Now:
```
[ERROR (main) 8.875µs]: *FATAL*: Missing data directory.
The path "elfshaker_data" is missing, so not in an elfshaker repository!
To create a new repository:
elfshaker store <snapshot name>
(This will create a new repo with a snapshot.)
To clone an existing repository:
elfshaker clone <url to esi> <directory>
Alternatively, you can set the environment variable ELFSHAKER_DATA
to point to a repository, or supply --data-dir to specify the
repository location.
```
It's a bit verbose but I hope more helpful to newcomers.
Previously we were failing during canonicalise, which has an internal existence check, before we reached our human-error type.
> Improve missing repo error

- src/repo/fs.rs
- src/repo/repository.rs
- test-scripts/check.sh
If a directory is being overwritten with a regular file, it's necessary to unlink everything in the directory first.
This was revealed by #141.
> Fix path changing between regular file and directory

- contrib/manyclangs-build-month
LLVM commit 7f3afab9181d83f92771293ad3b6c00ac62800fd added a dependency from llvm to the third-party directory. Make sure we check out and capture changes to this directory.
While we're here, add clang-tools-extra to the set of commits being considered for build. Note its absence means a small inaccuracy if you are trying to bisect a bug in a clang-tools-extra project which was caused by a commit which only modifies that directory.
> Add third-party directory to `git restore` and fix commit set

- contrib/manyclangs-setup.sh
On a default Ubuntu 20.04 install, `awk` points to `mawk`.
However, the manyclangs scripts use `awk -c` which is only supported by `gawk`.
> contrib/manyclangs-setup.sh: install gawk
